/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Returns the current logged-in user's profile
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logs out the user by clearing the HttpOnly refresh token cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Session
         * @description Refreshes an expired access token using HttpOnly refresh token cookie.
         */
        post: operations["refresh_session_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticates a user and returns a JWT access token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Registers a new user account.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Store an uploaded file and record it. Does not index it.
         *
         *     Upload and ingestion are two endpoints on purpose, which is why `uploaded`
         *     exists as a FileStatus value (restored 18 Aug). This one returns as soon as
         *     the bytes are safe; `POST /files/{file_id}/ingest` is what turns them into
         *     chunks.
         *
         *     `course_id` is read from the folder, never from the request. The client
         *     could send one, and a client that sends the wrong one would be writing a row
         *     that r42's composite foreign key rejects -- so the correct value is already
         *     known server-side, and asking for it only creates a way to be wrong.
         */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest File */
        post: operations["ingest_file_files__file_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete File */
        delete: operations["delete_file_files__file_id__delete"];
        options?: never;
        head?: never;
        /** Update File */
        patch: operations["update_file_files__file_id__patch"];
        trace?: never;
    };
    "/files/{file_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Content */
        get: operations["get_file_content_files__file_id__content_get"];
        /** Replace File */
        put: operations["replace_file_files__file_id__content_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rag/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_rag_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sessions
         * @description Get any latest sessions or by course ID
         */
        get: operations["get_sessions_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session By Session Id
         * @description Get session messages
         */
        get: operations["get_session_by_session_id_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion-runs/{ingestion_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Run */
        get: operations["get_ingestion_run_ingestion_runs__ingestion_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_courses_get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Course */
        delete: operations["delete_course_courses__course_id__delete"];
        options?: never;
        head?: never;
        /** Update Course */
        patch: operations["update_course_courses__course_id__patch"];
        trace?: never;
    };
    "/courses/{course_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_courses__course_id__folders_get"];
        put?: never;
        /** Create Folder */
        post: operations["create_folder_courses__course_id__folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Folder */
        get: operations["get_folder_courses__course_id__folders__folder_id__get"];
        put?: never;
        post?: never;
        /** Delete Folder */
        delete: operations["delete_folder_courses__course_id__folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Update Folder */
        patch: operations["update_folder_courses__course_id__folders__folder_id__patch"];
        trace?: never;
    };
    "/courses/{course_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Course Files */
        get: operations["list_course_files_courses__course_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Body_replace_file_files__file_id__content_put */
        Body_replace_file_files__file_id__content_put: {
            /** Upload */
            upload: string;
        };
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /**
             * Folder Id
             * Format: uuid
             */
            folder_id: string;
            /** Upload */
            upload: string;
        };
        /**
         * ChatRole
         * @enum {string}
         */
        ChatRole: "user" | "assistant";
        /**
         * Citation
         * @description Outbound: generation -> frontend, and persisted into MESSAGE.citations.
         *
         *     Deliberately anchored to file_id + page + quote and never to chunk_id:
         *     chunks are a regenerable intermediate product, while the file, the page and
         *     the quoted text survive re-ingestion.
         *
         *     Finding R14 asked for chunk-level provenance here. It goes in `ScopeSnapshot`
         *     instead: that recovers the traceability without making a citation depend on an
         *     id that a re-index invalidates. Resolved 18 Aug.
         */
        Citation: {
            /** Marker */
            marker: number;
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Filename */
            filename: string;
            /** Page */
            page?: number | null;
            /** Page End */
            page_end?: number | null;
            /**
             * Quote
             * @description Verbatim excerpt the model relied on. Must be findable in the source chunk; this is what makes a citation machine-checkable.
             */
            quote: string;
        };
        /**
         * Conversation
         * @description One conversation, one home course. Decision 1 (18 Aug), option A.
         *
         *     Ownership derives through `course -> user`. The `user_id` column that used
         *     to sit here was never ratified -- finding R1, closed 16 Aug -- and the
         *     `conversationcourselink` junction table went with it. Multi-course already
         *     exists one level down, on `Message.scope_course_id` plus
         *     `mentioned_file_ids`; the junction was a second mechanism for the same job.
         */
        Conversation: {
            /** Id */
            id?: string | null;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * Title
             * @default New Chat
             */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageRead"][];
        };
        /** CourseCreate */
        CourseCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Year */
            year: number;
            /** Sem */
            sem: number;
        };
        /** CourseRead */
        CourseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Year */
            year: number;
            /** Sem */
            sem: number;
            status: components["schemas"]["CourseStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CourseStatus
         * @enum {string}
         */
        CourseStatus: "active" | "archived";
        /** CourseUpdate */
        CourseUpdate: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            /** Year */
            year?: number | null;
            /** Sem */
            sem?: number | null;
            status?: components["schemas"]["CourseStatus"] | null;
        };
        /** DeleteSessionResponse */
        DeleteSessionResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * FileRead
         * @description Outbound shape for a file.
         */
        FileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Folder Id
             * Format: uuid
             */
            folder_id: string;
            /** Filename */
            filename: string;
            /** Storage Key */
            storage_key: string;
            /** Sha256 */
            sha256?: string | null;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Page Count */
            page_count?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "uploaded" | "processing" | "ready" | "failed";
            /** Error Message */
            error_message?: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Indexed At */
            indexed_at?: string | null;
        };
        /** FileUpdate */
        FileUpdate: {
            /** Filename */
            filename?: string | null;
            /** Folder Id */
            folder_id?: string | null;
        };
        /** FolderCreate */
        FolderCreate: {
            /** Name */
            name: string;
            /** Parent Folder Id */
            parent_folder_id?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** FolderRead */
        FolderRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /** Parent Folder Id */
            parent_folder_id: string | null;
            /** Name */
            name: string;
            /** Is Root */
            is_root: boolean;
            /** Sort Order */
            sort_order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FolderUpdate */
        FolderUpdate: {
            /** Name */
            name?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionResponse
         * @description Outbound shape for POST /files/{file_id}/ingest.
         *
         *     202, not 200: parsing a real lecture PDF measured 430.84 s on 31 Aug 2026
         *     against 0.02 s for the upload before it. Nothing holds an HTTP request open
         *     for seven minutes, so the endpoint acknowledges the work and hands back an id
         *     to poll -- CR-33.
         */
        IngestionResponse: {
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            /**
             * Ingestion Run Id
             * Format: uuid
             */
            ingestion_run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
            /** Chunk Count */
            chunk_count?: number | null;
            /** Error */
            error?: string | null;
        };
        /** IngestionRunRead */
        IngestionRunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * File Id
             * Format: uuid
             */
            file_id: string;
            status: components["schemas"]["IngestionRunStatus"];
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * IngestionRunStatus
         * @enum {string}
         */
        IngestionRunStatus: "queued" | "processing" | "ready" | "failed";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description Password must be at least 8 characters
             */
            password: string;
        };
        /** MessageRead */
        MessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Conversation Id
             * Format: uuid
             */
            conversation_id: string;
            /**
             * Scope Course Id
             * Format: uuid
             */
            scope_course_id: string;
            role: components["schemas"]["ChatRole"];
            /** Content */
            content: string;
            /** Grounded */
            grounded: boolean;
            /** Uncovered */
            uncovered: string | null;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[] | null;
            /** Mentioned File Ids */
            mentioned_file_ids: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RagAnswer
         * @description Outbound: generation -> frontend. Response model of POST /rag/query.
         */
        RagAnswer: {
            /** Answer */
            answer: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** Grounded */
            grounded: boolean;
            /**
             * Uncovered
             * @description What the sources did not cover, when they answered the question only in part. None means the answer is complete against the material -- r47. It is a field rather than a sentence inside `answer` so that `grounded=true` stops carrying two different meanings: answered in full, and answered in part.
             */
            uncovered?: string | null;
            /**
             * Used Chunks
             * @description How many chunks were actually put into the prompt, after selection. 0 means there was no material and the layer should have refused to answer.
             */
            used_chunks: number;
            /**
             * Conversation Id
             * @description The active or newly created conversation ID.
             */
            conversation_id?: string | null;
        };
        /**
         * RagQueryRequest
         * @description Inbound: frontend -> generation layer. A single question from the user.
         *
         *     Scope precedence, because the two scope fields can legitimately disagree:
         *
         *     - `file_ids` present -> it *is* the scope. Search exactly those files and
         *       ignore `course_id`, which is only the turn's home course.
         *     - `file_ids` null -> search the whole of `course_id`.
         *     - both null -> the whole corpus.
         *
         *     They must not be ANDed. US-12 (MVP, MUST) lets the @-picker mention files
         *     from any course, so `course_id AND file_id IN (...)` returns nothing at all
         *     whenever the user mentions a file from outside the course they are sitting
         *     in -- silently, with no error to trace.
         */
        RagQueryRequest: {
            /** Question */
            question: string;
            /**
             * Course Id
             * @description The turn's home course. Ignored when file_ids is set.
             */
            course_id?: string | null;
            /**
             * Conversation Id
             * @description The turn's conversation
             */
            conversation_id?: string | null;
            /**
             * File Ids
             * @description Explicit @-mention scope. May cross courses. When set, overrides course_id.
             */
            file_ids?: string[] | null;
            /**
             * Top K
             * @default 5
             */
            top_k: number;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters and at least 1 uppercase letter. Both rules are in the contract, so the client can check them before submitting.
             */
            password: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Missing, invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    refresh_session_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Email already exists */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_file_files__file_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_file_files__file_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_content_files__file_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_file_files__file_id__content_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_file_files__file_id__content_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_rag_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagAnswer"];
                };
            };
            /** @description Missing, invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Session or course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sessions_chat_sessions_get: {
        parameters: {
            query?: {
                /** @description Filter sessions by course ID */
                course_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
            /** @description Missing, invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_by_session_id_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Missing, invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteSessionResponse"];
                };
            };
            /** @description Missing, invalid or expired access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_run_ingestion_runs__ingestion_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingestion_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"][];
                };
            };
        };
    };
    create_course_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_courses__course_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_courses__course_id__folders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_folder_courses__course_id__folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folder_courses__course_id__folders__folder_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_courses__course_id__folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_courses__course_id__folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_course_files_courses__course_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
